### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by stweil** [ulb-sachsen-anhalt/ulb-zeitungsprojekt-hp1#3]
Are there any restrictions for the data which is provided in this repository? We use CC0 for our GT where possible, for example [here](https://github.com/UB-Mannheim/Fibeln).

**Comment by M3ssman** [comment]
Thanks for your remarks!
Your suggested license has been proposed to our management. 
Later this week there shall be a decision on that topic

**Comment by M3ssman** [comment]
It has been decided to use the Creative Commons Attribution 3.0 Germany License (not my choice)
Which means it can be used under nearly any conditions, but reference is desired

**Comment by stweil** [comment]
Thanks!
